# Generated by Django 3.0 on 2025-03-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingpage', '0003_auto_20250324_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_id', models.CharField(default=None, editable=False, max_length=8, unique=True)),
                ('organ_name', models.CharField(choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine')], max_length=20)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('age', models.PositiveIntegerField()),
                ('date_of_donation', models.DateField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.Hospital', to_field='hospital_email')),
            ],
        ),
    ]
