# Generated by Django 3.0 on 2025-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organavailability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='hospital_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='organ',
            name='hospital_name',
            field=models.CharField(default='defaulthospital', max_length=255),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
