# Generated by Django 3.0 on 2025-03-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseprediction', '0002_auto_20250324_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(upload_to='images/predicting_cataract/'),
        ),
    ]
